### ISSUE TITLE
Peer Review by Wilson Ciputra

### ISSUE THREAD

**Issue by wilsoncip** [harveenn/Term-Project-#4]
Hey Harveen,

Love how your website looks and the way you layout the page. Your HTML code is very organized and easy to read. I do have a few recommendations and suggestions for your code:

1. Your home.html should be named index.html. Most browsers would attempt to find index.html as the landing home page, otherwise, it might not select the correct landing page.
2. For your contact button on the navbar, your `<a>` tag is missing a closing `</a>` tag, and make sure it's fixed on every page. Without the closing tag, the contact link is clickable even from unrelated elements on the page. Make sure your navbar has the same dimensions and is consistent among all your pages. The navbar on your about me page shifts up slightly, so fixing this will make your website look neater.
3. For the images on your photos page, I would recommend using either `<table>` or using grids through `display: grid` in your CSS to organize the images. This would offer you more control over how the images are displayed. It will also ensure your image layout is responsive when the browser size changes.

In terms of content, I like the use of simplicity when displaying the photos. I do think that adding different "collections" or "galleries" will make the content more organized and attractive than a single photo page. I also think the about me page could use a bit more visuals to make the content pop even more.

Really great job with your website, it's very well made. 
Hopefully, these suggestions may help improve your website and good luck with the final version!

Best,
Wilson

**Comment by harveenn** [comment]
Hi Wilson! Thank you so much for your review. It was truly helpful. I made the index page change. I have changed my website greatly and I really appreciate all your input!
