### ISSUE TITLE
Peer Review - Drew Rowe 

### ISSUE THREAD

**Issue by drewrowe-babson** [harveenn/Term-Project-#5]
Tech Issue #1:
I cannot find your website anywhere on your GitHub. Also, you should change "homepage" to index.html so that it can be displayed on the domain. 

Tech Issue #2: 
Might want to center the navigation bar at the top of the page and add some image links to other pages in your website so that it looks like there is more substance to the website. 

Content #1: 
In general, the website could use more images with links to other pages or external sites to add more content to the overall website. 

Content #2: 
Maybe include highlights and interesting photos on the homepage so the user gets more of a feel for what the website is going to be about. Also it with engage the user more quickly.

**Comment by harveenn** [comment]
Hi Drew! Thank you so much for your feedback! I greatly appreciate it. I have incorporated a lot of your suggestions. I just kept my navigation bar on the side as I felt that it gave more of a portfolio look. But thank you so much!
